schema_version: 1

context:
  version: "0.2.0"
  python_min: "3.12"

package:
  name: tclean
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tclean/tclean-${{ version }}.tar.gz
  sha256: d9f43e1dd5738713b1e18136a868918f5dfe6fff7ab57c5e1c4625188d0c8a1c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pandas >=3.0.3
    - pandera >=0.31.1
    - scipy >=1.16.1

tests:
  - python:
      imports:
        - tclean
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Tools for cleaning, validating, and reconstructing time series.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ddahawkins-TUDelft/tclean
  repository: https://github.com/ddahawkins-TUDelft/tclean

extra:
  recipe-maintainers:
    - ddahawkins-TUDelft
